"use client";

import Image from "next/image";
import Link from "next/link";
import { useState, useTransition } from "react";
import { BookOpenText, Eye, Images, Pencil, Trash2, X } from "lucide-react";
import { Blog } from "@/lib/api/blogs";
import { Moment } from "@/lib/api/moments";
import { resolveImageUrl } from "@/lib/api/image-url";
import { deleteMyBlogAction, updateMyBlogAction } from "@/lib/actions/blog-action";
import { deleteMyMomentAction, updateMyMomentAction } from "@/lib/actions/moment-action";

type Selected = { type: "moment"; item: Moment } | { type: "blog"; item: Blog };
const badge = (status: string) => status === "approved" || status === "published" ? "bg-emerald-400/15 text-emerald-300" : status === "pending" ? "bg-amber-400/15 text-amber-300" : "bg-red-400/15 text-red-300";

export default function MySubmissions({ moments: initialMoments, blogs: initialBlogs }: { moments: Moment[]; blogs: Blog[] }) {
  const [moments, setMoments] = useState(initialMoments); const [blogs, setBlogs] = useState(initialBlogs); const [selected, setSelected] = useState<Selected | null>(null); const [editing, setEditing] = useState<Selected | null>(null); const [message, setMessage] = useState(""); const [pending, start] = useTransition();
  const remove = (entry: Selected) => { if (!confirm(`Delete this ${entry.type}?`)) return; start(async () => { const result = entry.type === "moment" ? await deleteMyMomentAction(entry.item.id) : await deleteMyBlogAction(entry.item.id); if (result.success) { entry.type === "moment" ? setMoments((all) => all.filter((x) => x.id !== entry.item.id)) : setBlogs((all) => all.filter((x) => x.id !== entry.item.id)); setMessage(result.message); } else setMessage(result.message); }); };
  const save = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; const data = new FormData(event.currentTarget); if (editing.type === "moment" && (!(data.get("image") instanceof File) || !(data.get("image") as File).size)) data.delete("image"); if (editing.type === "blog" && (!(data.get("coverImage") instanceof File) || !(data.get("coverImage") as File).size)) data.delete("coverImage"); start(async () => { const result = editing.type === "moment" ? await updateMyMomentAction(editing.item.id, data) : await updateMyBlogAction(editing.item.id, data); if (result.success && result.data) { editing.type === "moment" ? setMoments((all) => all.map((x) => x.id === editing.item.id ? result.data as Moment : x)) : setBlogs((all) => all.map((x) => x.id === editing.item.id ? result.data as Blog : x)); setEditing(null); } setMessage(result.message); }); };

  return <section className="overflow-hidden rounded-[14px] border border-[#e0a12b]/25 bg-[linear-gradient(135deg,#101820,#252827)] p-6 shadow-xl shadow-black/25">
    <div className="mb-6"><p className="text-2xl font-black text-white">My Submissions</p><p className="mt-1.5 text-sm text-[#aeb8c3]">View, edit, delete, and track your Trek Moments and blog stories.</p>{message && <p className="mt-3 text-sm text-[#e0a12b]">{message}</p>}</div>
    <div className="grid gap-6 lg:grid-cols-2">
      <Group title="My Trek Moments" icon={<Images size={19} />} action="Add moment" href="/dashboard/moments" empty={!moments.length}>{moments.map((item) => <Card key={item.id} image={item.image} title={item.title} date={item.createdAt} status={item.status} onView={() => setSelected({ type: "moment", item })} onEdit={() => setEditing({ type: "moment", item })} onDelete={() => remove({ type: "moment", item })} pending={pending} />)}</Group>
      <Group title="My Blog Stories" icon={<BookOpenText size={19} />} action="Add story" href="/dashboard/blogs/submit" empty={!blogs.length}>{blogs.map((item) => <Card key={item.id} image={item.coverImage} title={item.title} date={item.createdAt} status={item.status} onView={() => setSelected({ type: "blog", item })} onEdit={() => setEditing({ type: "blog", item })} onDelete={() => remove({ type: "blog", item })} pending={pending} />)}</Group>
    </div>
    {selected && <Modal title={selected.item.title} close={() => setSelected(null)}><Image src={resolveImageUrl(selected.type === "moment" ? selected.item.image : selected.item.coverImage)} alt={selected.item.title} width={800} height={420} unoptimized className="max-h-72 w-full rounded-xl object-cover" /><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-slate-300">{selected.type === "moment" ? selected.item.caption : selected.item.content}</p></Modal>}
    {editing && <Modal title={`Edit ${editing.type}`} close={() => setEditing(null)}><form onSubmit={save} className="grid gap-4"><input name="title" required defaultValue={editing.item.title} className="h-12 rounded-xl bg-white/5 px-4" />{editing.type === "moment" ? <><textarea name="caption" required defaultValue={editing.item.caption} rows={5} className="rounded-xl bg-white/5 p-4" /><input name="location" required defaultValue={editing.item.location} className="h-12 rounded-xl bg-white/5 px-4" /><input name="trailSlug" defaultValue={editing.item.trailSlug} placeholder="Trail slug" className="h-12 rounded-xl bg-white/5 px-4" /><input name="image" type="file" accept="image/*" className="rounded-xl border border-white/10 p-3" /></> : <><textarea name="description" required defaultValue={editing.item.description} rows={3} className="rounded-xl bg-white/5 p-4" /><textarea name="content" required defaultValue={editing.item.content} rows={7} className="rounded-xl bg-white/5 p-4" /><input name="readingTime" required defaultValue={editing.item.readingTime} className="h-12 rounded-xl bg-white/5 px-4" /><input name="relatedTrailSlugs" defaultValue={JSON.stringify(editing.item.relatedTrailSlugs)} type="hidden" /><input name="coverImage" type="file" accept="image/*" className="rounded-xl border border-white/10 p-3" /></>}<p className="text-xs text-amber-300">After editing, this submission will require admin approval again.</p><button disabled={pending} className="rounded-xl bg-[#e0a12b] px-5 py-3 font-black text-black">{pending ? "Saving..." : "Save changes"}</button></form></Modal>}
  </section>;
}

function Group({ title, icon, action, href, empty, children }: { title: string; icon: React.ReactNode; action: string; href: string; empty: boolean; children: React.ReactNode }) { return <div className="min-w-0 rounded-xl border border-white/10 bg-[#101820] p-4"><div className="mb-4 flex items-center justify-between"><h3 className="flex items-center gap-2 font-black text-white"><span className="text-[#e0a12b]">{icon}</span>{title}</h3><Link href={href} className="text-xs font-black text-[#e0a12b]">{action}</Link></div><div className="grid gap-3">{empty ? <p className="rounded-lg border border-dashed border-white/10 p-4 text-sm text-[#aeb8c3]">No submissions yet.</p> : children}</div></div>; }
function Card({ image, title, date, status, onView, onEdit, onDelete, pending }: { image: string; title: string; date: string; status: string; onView: () => void; onEdit: () => void; onDelete: () => void; pending: boolean }) { return <article className="min-w-0 overflow-hidden rounded-lg border border-white/10 bg-white/[0.025] p-3"><div className="grid grid-cols-[64px_minmax(0,1fr)_auto] items-center gap-3"><div className="relative h-14 w-16 overflow-hidden rounded-lg"><Image src={resolveImageUrl(image)} alt={title} fill unoptimized className="object-cover" /></div><div className="min-w-0"><p className="truncate text-sm font-black text-white" title={title}>{title}</p><p className="mt-1 text-xs text-[#8f9ba8]">{new Date(date).toLocaleDateString()}</p></div><span className={`whitespace-nowrap rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${badge(status)}`}>{status === "draft" ? "Rejected" : status}</span></div><div className="mt-3 flex justify-end gap-2 border-t border-white/10 pt-3"><button onClick={onView} className="flex items-center gap-1 text-xs text-sky-300"><Eye size={13} />View</button><button onClick={onEdit} className="flex items-center gap-1 text-xs text-amber-300"><Pencil size={13} />Edit</button><button disabled={pending} onClick={onDelete} className="flex items-center gap-1 text-xs text-red-300"><Trash2 size={13} />Delete</button></div></article>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/80 p-4"><div className="my-8 w-full max-w-2xl rounded-3xl border border-white/10 bg-[#101925] p-6 text-white"><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-black">{title}</h2><button onClick={close}><X /></button></div>{children}</div></div>; }
