"use client";
import { useState, useTransition } from "react";
import Image from "next/image";
import { AdminMoment } from "@/lib/api/admin/admin-moments";
import { resolveImageUrl } from "@/lib/api/image-url";
import { deleteAdminMomentAction, updateAdminMomentAction } from "@/lib/actions/admin/admin-moment-action";

export default function MomentTable({ initial }: { initial: AdminMoment[] }) {
  const [items, setItems] = useState(initial); const [editing, setEditing] = useState<AdminMoment | null>(null); const [pending, start] = useTransition();
  const update = (item: AdminMoment, payload: Parameters<typeof updateAdminMomentAction>[1]) => start(async () => { const r = await updateAdminMomentAction(item.id, payload); if (r.success && r.data) setItems((all) => all.map((x) => x.id === item.id ? r.data as AdminMoment : x)); });
  return <div className="space-y-4">{items.length ? items.map((item) => <article key={item.id} className="grid gap-5 rounded-2xl border border-white/10 bg-[#101925] p-5 md:grid-cols-[150px_1fr_auto]">
    <div className="relative h-32 overflow-hidden rounded-xl"><Image src={resolveImageUrl(item.image)} alt={item.title} fill unoptimized className="object-cover" /></div>
    <div><div className="flex flex-wrap items-center gap-3"><h2 className="text-lg font-black">{item.title}</h2><span className={`rounded-full px-3 py-1 text-xs font-black ${item.status === "approved" ? "bg-emerald-400/15 text-emerald-300" : item.status === "rejected" ? "bg-red-400/15 text-red-300" : "bg-amber-400/15 text-amber-300"}`}>{item.status}</span></div><p className="mt-2 text-sm text-slate-400">{item.caption}</p><p className="mt-3 text-xs text-slate-500">{item.location} · By {item.uploadedBy.fullName}</p></div>
    <div className="flex flex-wrap content-start gap-2 md:w-36">{item.status !== "approved" && <button disabled={pending} onClick={() => update(item, { status: "approved" })} className="rounded-lg bg-emerald-500 px-3 py-2 text-xs font-black text-white">Approve</button>}<button disabled={pending} onClick={() => update(item, { status: "rejected" })} className="rounded-lg border border-red-400/30 px-3 py-2 text-xs font-bold text-red-300">Reject</button><button onClick={() => setEditing(item)} className="rounded-lg border border-white/15 px-3 py-2 text-xs font-bold">Edit</button><button disabled={pending} onClick={() => { if (confirm("Delete this moment?")) start(async () => { const r = await deleteAdminMomentAction(item.id); if (r.success) setItems((all) => all.filter((x) => x.id !== item.id)); }); }} className="rounded-lg border border-red-400/30 px-3 py-2 text-xs font-bold text-red-300">Delete</button></div>
  </article>) : <div className="rounded-2xl border border-white/10 p-12 text-center text-slate-400">No moments submitted yet.</div>}
  {editing && <div className="fixed inset-0 z-50 grid place-items-center bg-black/80 p-4"><form className="grid w-full max-w-xl gap-4 rounded-3xl border border-white/10 bg-[#101925] p-6" onSubmit={(e) => { e.preventDefault(); const d = new FormData(e.currentTarget); update(editing, { title: String(d.get("title")), caption: String(d.get("caption")), location: String(d.get("location")), trailSlug: String(d.get("trailSlug") || "") || undefined }); setEditing(null); }}><h2 className="text-2xl font-black">Edit moment</h2><input name="title" defaultValue={editing.title} className="h-12 rounded-xl bg-white/5 px-4" /><textarea name="caption" defaultValue={editing.caption} rows={5} className="rounded-xl bg-white/5 p-4" /><input name="location" defaultValue={editing.location} className="h-12 rounded-xl bg-white/5 px-4" /><input name="trailSlug" defaultValue={editing.trailSlug} className="h-12 rounded-xl bg-white/5 px-4" /><div className="flex justify-end gap-3"><button type="button" onClick={() => setEditing(null)}>Cancel</button><button className="rounded-xl bg-[#D89A2B] px-5 py-2.5 font-black text-black">Save</button></div></form></div>}
  </div>;
}
